# Generated by Django 5.0 on 2025-09-28 23:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('user_count', models.PositiveIntegerField(default=0)),
                ('users', models.ManyToManyField(related_name='petitions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
