# Generated by Django 5.0 on 2025-09-30 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='petition',
            old_name='users',
            new_name='voters',
        ),
        migrations.RenameField(
            model_name='petition',
            old_name='user_count',
            new_name='votes',
        ),
        migrations.AddField(
            model_name='petition',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
